### ISSUE TITLE
resizeToFill and fullscreen (or any screen change)

### ISSUE THREAD

**Issue by Hypher** [ekelokorpi/panda.js#118]
Hello!
When config.System.resizeToFill = true, the game fills the screen. But on screen resize (typically going/leaving fullscreen) it does not fill it anymore.
This is firstly prevented by this._resizeToFill = true; that avoids the re-execution of the game.system.resizeToFill() method. And even if I remove this guard, calling resizeToFill again does not fix the thing (here I need you).
Thank you!

**Comment by Hypher** [comment]
I tested on two different Android phones. Here what happens:
After removing the _resizeToFill = true guard:
- load your first scene (that means rotate in landscape)
- enter fullscreen calling game.fullscreen(); => the canvas does not take 100% height, there is a little space below
- leave fullscreen (swipe down) => the canvas is smaller than the screen in both width and height, and not centered. Its width and height are larger than initially
- reenter fullscreen => canvas not fullscreen

The canvas CSS size is slightly modified, but it seems like this is mainly the document size which grows unexpectedly...

**Comment by Hypher** [comment]
Ok I got it...
The canvas fills the entire screen.
This is the stage.width/height and system.width/height that grow to very high values (like 3367x1510). How are they computed and why does they grow like that?

**Comment by Hypher** [comment]
Ok since you multiply system.width/height by the screen ratio in resizeToFill, it does not stop to grow.
So before that I reset the other height/with to original game.System.height/width. That does the trick.
That's ok for system.width/height.
**But why then *sometimes* my scene width/height comes to be greater than my system.width/height ?**

**Comment by Hypher** [comment]
When I say *sometimes*, it means it's totally random. Sometimes the stage is like twice larger than the system, sometimes its equal, but seems like it could be any value. Just play with enter/leave fullscreen and rotate portrait/landscape, and the game never appears the same.

**Comment by Ninjadoodle** [comment]
I'm having tho issue also. When requesting fullscreen on Android with resizeToFill enabled, the game leaves a big white bar/space where the navigation bar was, instead of filling the rest of the space.

**Comment by Hypher** [comment]
My commit fixes that

**Comment by Ninjadoodle** [comment]
Hi Hypher

Sorry for being a bit dumb using github, but do I just download the develop version in order to fix this issue?

Thank you in advance!

**Comment by Ninjadoodle** [comment]
Sorry, please disregard ... I found your commit :)

**Comment by ekelokorpi** [comment]
This will be fixed on 1.14.0
