### ISSUE TITLE
document.requestFullscreen prevents rotateScreen to appear

### ISSUE THREAD

**Issue by Hypher** [ekelokorpi/panda.js#119]
When going fullscreen using document.requestFullscreen, the rotate screen does not show anymore. Instead there is just a blank screen :(

**Comment by ekelokorpi** [comment]
Thanks for the info, what device/browser are you using?

**Comment by Hypher** [comment]
I'm using Chrome 36 on Android 4.2.2.
Note that:
- in portrait, going fullscreen => the rotate screen appears ;
- then rotating the device landscape => the canvas is not fullscreen (see my other bug)
- going back in portrait => rotate screen appears. No problem.
But:
- in landscape, going fullscreen => canvas size is ok
- rotating in portrait => blank screen

**Comment by Hypher** [comment]
Ok I just tested on another android.
Forget what I said above, that was probably a cache bug.
So the bug appears only when using document.requestFullscreen and being fullscreen on portrait orientation.
There is no trick rotating the device twice etc...
So it's just calling document.requestFullscreen in portrait mode => blank screen.

**Comment by ekelokorpi** [comment]
This will be fixed on 1.14.0
