### ISSUE TITLE
Error install in linux

### ISSUE THREAD

**Issue by goids** [ekelokorpi/panda.js#120]
I installed panda.js in npm, when income instruction ``` panda install ``` shows the following.

``` Installing Panda.js engine...
Error creating temp dir ```

**Comment by ekelokorpi** [comment]
It seems that your node does not have permission to make new dir

**Comment by goids** [comment]
yes. that was the problem. thank you very much

**Comment by ekelokorpi** [comment]
No problem! Sorry for my delayed reply

**Comment by goids** [comment]
Quiet no problem, I am now is trying to create a method to make a test game shooter.

but now I'm writing for the forum the problem I'm having.
