### ISSUE TITLE
Next version : UI system ?

### ISSUE THREAD

**Issue by FishTFM** [ekelokorpi/panda.js#125]
Hey !
Shouldn't be cool to have a complete UI system on the next release of PandaJS ?

At least, buttons, inputs canvas based (not using DOM), textfield (with selections and shortcut), some grid system, containers with scrollbars ?

Looks cool if you like my suggestion ^^

**Comment by ekelokorpi** [comment]
I would see that as a plugin instead.

**Comment by FishTFM** [comment]
I'm done with the Button plugin and should working on the Input plugin but be a part of the core could makes Panda more popular and used ^^

**Comment by ekelokorpi** [comment]
Not all games need inputs or textfields and i want to keep the core as clean and small as possible, that's why i rather would see those as plugins.

**Comment by FishTFM** [comment]
Ah ! Not think about this, you're right ^^'
